# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudClipboardGo < Formula
  desc "云剪贴板：跨设备共享文本和文件"
  homepage "https://github.com/Jonnyan404/cloud-clipboard-go"
  version "5.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jonnyan404/cloud-clipboard-go/releases/download/v5.2.1/CCG_server-darwin-x86_64-v5.2.1.tar.gz"
      sha256 "9558d6b5c6bb8d1934ef6db03063b5329ea7dd66a93fbacf6a037cd65cabe5c4"

      define_method(:install) do
        bin.install "cloud-clipboard-go"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Jonnyan404/cloud-clipboard-go/releases/download/v5.2.1/CCG_server-darwin-aarch64-v5.2.1.tar.gz"
      sha256 "380f57f979f4bb0b8ac5cb5d2bd87d693e7dd3e88b0d3d35f0b005aa96fdc1e8"

      define_method(:install) do
        bin.install "cloud-clipboard-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jonnyan404/cloud-clipboard-go/releases/download/v5.2.1/CCG_server-linux-x86_64-v5.2.1.tar.gz"
      sha256 "5cc5b944aab013223cbdb090371e46966db8834d390e41c45dbfa4c011aea804"
      define_method(:install) do
        bin.install "cloud-clipboard-go"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jonnyan404/cloud-clipboard-go/releases/download/v5.2.1/CCG_server-linux-aarch64-v5.2.1.tar.gz"
      sha256 "32219ee6e8ed1e166c88301ff5b648ab4c2159b8f53fa9f0830a51e4407606a1"
      define_method(:install) do
        bin.install "cloud-clipboard-go"
      end
    end
  end

  def post_install
    (etc/"cloud-clipboard-go").mkpath
    (var/"log").mkpath
    # 如果配置文件不存在，创建一个默认配置
    unless (etc/"cloud-clipboard-go/config.json").exist?
      (etc/"cloud-clipboard-go/config.json").write <<~EOS
        {
          "server": {
            "host": "0.0.0.0",
            "port": 9501
          }
        }
      EOS
    end
  end

  service do
    run [opt_bin/"cloud-clipboard-go", "-config", etc/"cloud-clipboard-go/config.json"]
    working_dir var
    keep_alive true
    log_path var/"log/cloud-clipboard-go.log"
    error_log_path var/"log/cloud-clipboard-go.error.log"
  end

  test do
    system "#{bin}/cloud-clipboard-go", "-v"
  end
end
