# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudClipboardGo < Formula
  desc "云剪贴板：跨设备共享文本和文件"
  homepage "https://github.com/Jonnyan404/cloud-clipboard-go"
  version "5.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jonnyan404/cloud-clipboard-go/releases/download/v5.0.5/cloud-clipboard-go_Darwin_x86_64.tar.gz"
      sha256 "625eec8cd0459d3990b2a71f40c1493c97f9150bfafff88072d7bd5454945fa8"

      define_method(:install) do
        bin.install "cloud-clipboard-go"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Jonnyan404/cloud-clipboard-go/releases/download/v5.0.5/cloud-clipboard-go_Darwin_aarch64.tar.gz"
      sha256 "5d881752cdf286a4f8b7d249ba33ac4ac3743196eee9b65b147ac1d30d37a8e4"

      define_method(:install) do
        bin.install "cloud-clipboard-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jonnyan404/cloud-clipboard-go/releases/download/v5.0.5/cloud-clipboard-go_Linux_x86_64.tar.gz"
      sha256 "2a3f522ca176e332e9c9b60b61b9149b07e858bbb9fbb74ff6da17f5bafce85a"
      define_method(:install) do
        bin.install "cloud-clipboard-go"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jonnyan404/cloud-clipboard-go/releases/download/v5.0.5/cloud-clipboard-go_Linux_aarch64.tar.gz"
      sha256 "c9f6139b43eee43508624d18037d4e3051782097862d3f1cd455a277a181277a"
      define_method(:install) do
        bin.install "cloud-clipboard-go"
      end
    end
  end

  def post_install
    (etc/"cloud-clipboard-go").mkpath
    (var/"log").mkpath
    # 如果配置文件不存在，创建一个默认配置
    unless (etc/"cloud-clipboard-go/config.json").exist?
      (etc/"cloud-clipboard-go/config.json").write <<~EOS
        {
          "server": {
            "host": "0.0.0.0",
            "port": 9501
          }
        }
      EOS
    end
  end

  service do
    run [opt_bin/"cloud-clipboard-go", "-config", etc/"cloud-clipboard-go/config.json"]
    working_dir var
    keep_alive true
    log_path var/"log/cloud-clipboard-go.log"
    error_log_path var/"log/cloud-clipboard-go.error.log"
  end

  test do
    system "#{bin}/cloud-clipboard-go", "-v"
  end
end
