# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudClipboard < Formula
  desc "云剪贴板：跨设备共享文本和文件"
  homepage "https://github.com/Jonnyan404/cloud-clipboard-go"
  version "2.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jonnyan404/cloud-clipboard-go/releases/download/v2.9/cloud-clipboard-go_Darwin_x86_64.tar.gz"
      sha256 "8810bf2b2cde241a5b2fb74602097696be4aeccf7622f53fbd41e06aac099aef"

      def install
        bin.install "cloud-clipboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Jonnyan404/cloud-clipboard-go/releases/download/v2.9/cloud-clipboard-go_Darwin_aarch64.tar.gz"
      sha256 "df120ca6125cebf7db5bc30e5c916e87fa90668e6c0ed186da670c12c3d5a0fd"

      def install
        bin.install "cloud-clipboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Jonnyan404/cloud-clipboard-go/releases/download/v2.9/cloud-clipboard-go_Linux_x86_64.tar.gz"
        sha256 "031bf3df91f45e41e716db88b51bbcb6728b5ed46c012babdc269bb2d9eeafaf"

        def install
          bin.install "cloud-clipboard"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Jonnyan404/cloud-clipboard-go/releases/download/v2.9/cloud-clipboard-go_Linux_aarch64.tar.gz"
        sha256 "a09fee9257b685db2bd0503f772e1e01d07df38ad6c081a0b3f5e5d1fa7ec24c"

        def install
          bin.install "cloud-clipboard"
        end
      end
    end
  end

  def post_install
    (etc/"cloud-clipboard").mkpath
    (var/"log").mkpath
    # 如果配置文件不存在，创建一个默认配置
    unless (etc/"cloud-clipboard/config.json").exist?
      (etc/"cloud-clipboard/config.json").write <<~EOS
        {
          "server": {
            "host": "0.0.0.0",
            "port": 9502
          }
        }
      EOS
    end
  end

  service do
    run [opt_bin/"cloud-clipboard", "--config", etc/"cloud-clipboard/config.json"]
    working_dir var
    keep_alive true
    log_path var/"log/cloud-clipboard.log"
    error_log_path var/"log/cloud-clipboard.error.log"
  end

  test do
    system "#{bin}/cloud-clipboard", "--version"
  end
end
