# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudClipboardGo < Formula
  desc "云剪贴板：跨设备共享文本和文件"
  homepage "https://github.com/Jonnyan404/cloud-clipboard-go"
  version "5.0.7-beta4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jonnyan404/cloud-clipboard-go/releases/download/v5.0.7-beta4/CCG_server-darwin-x86_64-v5.0.7-beta4.tar.gz"
      sha256 "6dda32a330ff5f758ee0370114bf99a2d9026457f46284e119dff9cb223373d6"

      define_method(:install) do
        bin.install "cloud-clipboard-go"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Jonnyan404/cloud-clipboard-go/releases/download/v5.0.7-beta4/CCG_server-darwin-aarch64-v5.0.7-beta4.tar.gz"
      sha256 "804faf50e399b61d48f177e7f1449962d58915aa8c37397cd22ea89ab60400f5"

      define_method(:install) do
        bin.install "cloud-clipboard-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jonnyan404/cloud-clipboard-go/releases/download/v5.0.7-beta4/CCG_server-linux-x86_64-v5.0.7-beta4.tar.gz"
      sha256 "ae8de908025d6b228297aa371149c08e3f999bb61cbdfb788a4603c3fcb50bbc"
      define_method(:install) do
        bin.install "cloud-clipboard-go"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jonnyan404/cloud-clipboard-go/releases/download/v5.0.7-beta4/CCG_server-linux-aarch64-v5.0.7-beta4.tar.gz"
      sha256 "4f85ec2573b7fb21e4dc1171747b2cd7dce309bb7c6b544c5022edd8440f8b70"
      define_method(:install) do
        bin.install "cloud-clipboard-go"
      end
    end
  end

  def post_install
    (etc/"cloud-clipboard-go").mkpath
    (var/"log").mkpath
    # 如果配置文件不存在，创建一个默认配置
    unless (etc/"cloud-clipboard-go/config.json").exist?
      (etc/"cloud-clipboard-go/config.json").write <<~EOS
        {
          "server": {
            "host": "0.0.0.0",
            "port": 9501
          }
        }
      EOS
    end
  end

  service do
    run [opt_bin/"cloud-clipboard-go", "-config", etc/"cloud-clipboard-go/config.json"]
    working_dir var
    keep_alive true
    log_path var/"log/cloud-clipboard-go.log"
    error_log_path var/"log/cloud-clipboard-go.error.log"
  end

  test do
    system "#{bin}/cloud-clipboard-go", "-v"
  end
end
