# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudClipboard < Formula
  desc "云剪贴板：跨设备共享文本和文件"
  homepage "https://github.com/Jonnyan404/cloud-clipboard-go"
  version "3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jonnyan404/cloud-clipboard-go/releases/download/v3.0/cloud-clipboard-go_Darwin_x86_64.tar.gz"
      sha256 "d1b6b367001b0882218409e48637f7a38338cd7cbfd4c07e39a2d3ae2357491e"

      def install
        bin.install "cloud-clipboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Jonnyan404/cloud-clipboard-go/releases/download/v3.0/cloud-clipboard-go_Darwin_aarch64.tar.gz"
      sha256 "e664ab04a51fc36dd8d007729ec1bf0a2f31c66c4bd1f3f981c3d476dc7317db"

      def install
        bin.install "cloud-clipboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Jonnyan404/cloud-clipboard-go/releases/download/v3.0/cloud-clipboard-go_Linux_x86_64.tar.gz"
        sha256 "83d8af290443bee48ef8e705c725e34d4b0ddf75aa18722643b44c8f2145d37b"

        def install
          bin.install "cloud-clipboard"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Jonnyan404/cloud-clipboard-go/releases/download/v3.0/cloud-clipboard-go_Linux_aarch64.tar.gz"
        sha256 "9ac6356e1e0038c962fbd49ac3e5e3afcadb9fa7d42da6293b753a8ecf756770"

        def install
          bin.install "cloud-clipboard"
        end
      end
    end
  end

  def post_install
    (etc/"cloud-clipboard").mkpath
    (var/"log").mkpath
    # 如果配置文件不存在，创建一个默认配置
    unless (etc/"cloud-clipboard/config.json").exist?
      (etc/"cloud-clipboard/config.json").write <<~EOS
        {
          "server": {
            "host": "0.0.0.0",
            "port": 9502
          }
        }
      EOS
    end
  end

  service do
    run [opt_bin/"cloud-clipboard", "--config", etc/"cloud-clipboard/config.json"]
    working_dir var
    keep_alive true
    log_path var/"log/cloud-clipboard.log"
    error_log_path var/"log/cloud-clipboard.error.log"
  end

  test do
    system "#{bin}/cloud-clipboard", "--version"
  end
end
